name: BE deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: docker build -f docker/build/Dockerfile -t be-app .
      - name: Remove old container
        run: docker rm -f be-app || true
      - name: Deploy
        env:
          AI_CORE_BASE_URL: ${{ vars.ai_core_base_url }}
          AI_CORE_PROMPT_ENDPOINT: ${{ vars.ai_core_prompt_endpoint }}
          AI_CORE_EDIT_ENDPOINT: ${{ vars.ai_core_edit_endpoint }}
          AI_CORE_GEN_ICON_ENDPOINT: ${{ vars.ai_core_gen_icon_endpoint }}
          AI_CORE_GEN_CODE_ENDPOINT: ${{ vars.ai_core_gen_code_endpoint }}
          AI_CORE_GEN_ANSIBLE_ENDPOINT: ${{ vars.ai_core_gen_ansible_endpoint }}
          SERVER_PORT: ${{ vars.server_port }}
        run: 'docker run -d -e AI_CORE_BASE_URL -e AI_CORE_PROMPT_ENDPOINT -e AI_CORE_EDIT_ENDPOINT -e AI_CORE_GEN_ICON_ENDPOINT -e AI_CORE_GEN_CODE_ENDPOINT -e AI_CORE_GEN_ANSIBLE_ENDPOINT -p 8080:${{ vars.server_port }} --name be-app be-app'
