name: BE Test
on: [push]
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: docker build -f docker/test/Dockerfile -t be-test .
      - name: Test
        run: docker run be-test
